### ISSUE TITLE
Forge Update

### ISSUE THREAD

**Issue by louisw22** [MinecraftPortCentral/Cauldron-Issues#143]
Is there a way to update the forge version to the latest on cauldron?

**Comment by Thornbush42** [comment]
Yes, you have to update Cauldron to a newer version. Now, due to several reasons, Cauldron have very little in the way of downloads due to a take-down of their content. However, some nice people are hosting their files for them. Install a _NEW_ version of Cauldron by doing the following:

Download the top option on this page (cauldron-1.7.10-1.1307.06.218.zip): http://tcpr.ca/cauldron
Download the Minecraft server (click on "server jar" next to 1.7.10): https://mcversions.net/
Download the "Run.bat" server launch file: https://www.dropbox.com/s/0oeaibkljpe2okx/Run.bat?dl=0

A) Create a new folder, called "New Server" for example,
B) Put ".jar" file and "libraries" folder (from the "cauldron-1.7.10-1.1307.06.218.zip") into the "New Server" folder (using WinRAR or similar programs),
C) Put the "minecraft-server.1.7.10.jar" into the "New Server" folder,
D) Put the "Run.bat" file into the "New Server" folder,
E) Double-click on the "cauldron-1.7.10-1.1307.06.218-server.jar" (expect nothing to happen),
F) Put the mods & configs in the correct directory,
G) (OPTIONAL) Put the "cauldronbukkit-1.7.10-1.1207.01.198.jar" file in the "New Server" folder
H) Briefly run the server by opening the "Run.bat"
I) (OPTIONAL) Close the server once finished, then you may put any plugins into the correct directory in the "New Server" folder.
J) If any problems occur during launch of the server, accept the EULA in the "eula.txt" by change the "false" value in the file to "true".

~Note: If you want to _UPDATE_ your Cauldron server then place all files into your existing server folder, remembering to select "Replace existing files" if asked.

**Comment by Thornbush42** [comment]
P.S. If this has solved your issue/question, please close this.

**Comment by louisw22** [comment]
Thanks

**Comment by cghdxx** [comment]
where do I get the cauldronbukkit-1.7.10-1.1207.01.198.jar?

**Comment by Thornbush42** [comment]
You can get the "cauldronbukkit-1.7.10-1.1207.01.198.jar" from the same website as "Cauldron" (http://tcpr.ca/cauldron)

**Comment by keksbg** [comment]
Hello, I have a problem when i started it using run.bat.
It says: 
C:\Users\Vasil\Desktop\Mods 1.7.10 server Bukkit>java -Xms1G -Xmx4G -jar cauldro
n-1.7.10-1.1307.06.218-server.jar nogui
Error: Unable to access jarfile cauldron-1.7.10-1.1307.06.218-server.jar

C:\Users\Vasil\Desktop\Mods 1.7.10 server Bukkit>PAUSE
Press any key to continue . . .
If you can help me this would be great!
Thanks
- lbdBG (Vasil Bakalov)

**Comment by vico93** [comment]
This rep and (of course) Cauldron (official) developement is dead since wolvereness's bukkit DCMA.

BUT, we have a lifeboat: KCauldron: https://gitlab.prok.pw/Prototik/KCauldron
Download the KCauldron build in Yive Mirror (http://tcpr.ca/cauldron). If the issue persists, login and repost the issue in that rep!

**Comment by lucas0017** [comment]
@lbdBG You probably have a newer version of cauldron so open your server file, find your cauldron server jar, right click on it, click rename, highlight the section of numbers at the end of the file name (mine was 1.7.10-2.1403.1.54) , click copy, go to your server file, right click on Run.bat, click edit, highlight: "1.7.10-1.1307.06.218", delete it, click paste where the existing set of numbers was, click file and save it.    That should work its what i did

**Comment by A2-TheDam** [comment]
My server is crashing when i try to start it. I am running mac os el capitan. This is what the console says: Generating keypair
[22:25:44 INFO]: Starting Minecraft server on _:25565
[22:25:45 WARN]: *_*\* FAILED TO BIND TO PORT!
[22:25:45 WARN]: The exception was: java.net.BindException: Address already in use
[22:25:45 WARN]: Perhaps a server is already running on that port?
[22:25:45 WARN]: Can't revert to frozen GameData state without freezing first.
[22:25:45 INFO]: Applying holder lookups
[22:25:45 INFO]: Holder lookups applied
[22:25:45 INFO]: The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.

> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.

[Process completed]

-Please help

**Comment by MuresanSergiu** [comment]
@Chock500 it basically means you already are using the port 25565 for another Minecraft server instance. Just change the port in the configs to fix this issue or terminate all the other instances.

**Comment by A2-TheDam** [comment]
Thank you, that makes sense

**Comment by A2-TheDam** [comment]
I am having another issue, when i try to join the server, it says logging in and the server console says my UUID, but nothing happens. What do i do now?

edit: i figured it out, my client didn't have forge installed

**Comment by Ycmelon** [comment]
Hey guys... thanks for the posts :smile: ... but I have a problem...
My mods are there but my plugins aren't...
How do I fix this? Thanks :grinning: 
Btw if your commands don't work, try using "minecraft:" without the "s in front of the command
:sunglasses:

**Comment by vico93** [comment]
AGAIN

This rep and (of course) Cauldron (official) developement is dead since wolvereness's bukkit DCMA.

BUT, we have a lifeboat: KCauldron: https://gitlab.prok.pw/Prototik/KCauldron
Download the KCauldron build in Yive Mirror (http://tcpr.ca/cauldron). If the issue persists, login and repost the issue in that rep!

**Comment by Ycmelon** [comment]
yay
