### ISSUE TITLE
TFC Forge vs Bukkit Inventory

### ISSUE THREAD

**Issue by Azaysol** [MinecraftPortCentral/Cauldron-Issues#89]
When running any type of econ with a buy/sell shop the item never reaches the player and instead just disapears. However the plugin thinks it worked correctly and take the money+the item from the shop.

i have tried this with singshop and essentials shop
cauldron:209
tfc:79.12
essentails: 2.13.1
sign shop 2.9.1

Forum post with more details
http://cauldron.minecraftforge.net/threads/terrafirmacraft-giving-items.368/#post-3635

This issue also happens when trying to give yourself items in creative mode

**Comment by bloodmc** [comment]
Just fixed it =) Fix will be included in my next release.

**Comment by Azaysol** [comment]
thanks again ^ ^

**Comment by Graitt** [comment]
Sorry for asking, but just gotta know for sure in order to progress with setting up the 1.6.4TFC project.

Will this fix be only applied to the latest 1.7.10 cauldron, or the 1,6,4 aswell?

**Comment by bloodmc** [comment]
@Graitt I'll add the fix to 1.6.4 later this week when I get some more time.

**Comment by Graitt** [comment]
That's more than we can ask. Thank you very much.

**Comment by Jaina47** [comment]
@bloodmc 
I'm sorry is it fixed in 1.6.4 already? Or you will notify us in this topic?
Thank you so much! Our server runs 1.6.4. so we realy need it! Cant wait for this fix!

**Comment by Graitt** [comment]
@bloodmc 
Tested with /essentials /chestshop - those issues are gone, thank you very much.

Also a quick question if I may
TFC mod brings a lot of simple tileentities (replacing even the dirt\grass\stone), and I belive it's the reason for a lot of console spam

[WARNING] Queued further Chunk unloading due to hitting TileEntity limit

I know it's ok and I will disable it from logging, but I'm not sure of how to raise the limit.
Because the unloading spam starts on an empty server and does not stop, which I think is a bit wrong for a TFC server.

**Comment by Jaina47** [comment]
@bloodmc 
OMG! I love you! It's worcking! I thought we were doomed, but you saved us. Thank you!

**Comment by Sirse** [comment]
@bloodmc, can you post updated cauldron 1.6.4 source codes on torrents? We have only 1.7.2 release from Maeyanie site (

**Comment by Jaina47** [comment]
@Sirse 
http://cauldron.minecraftforge.net/threads/cauldroninstallerpatch-1-965-01-205.741/

**Comment by Sirse** [comment]
@Jaina47, it's not source code, it just binary patch for compiled server jar
