### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 6

### ISSUE THREAD

**Issue by thisischrys** [MinecraftPortCentral/Cauldron-Issues#96]
When installing latest voxelmodpackplugin (http://goo.gl/UhYN9f) I get the following error as soon as a player connects:

lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 6

Server doesn't crash but nobody can connect. The mods of the plugin seem to think it's an issue with Cauldron's deobfuscation transformers. (also on http://goo.gl/UhYN9f)

It works fine on just a bukkit server.

**Comment by thisischrys** [comment]
dead

**Comment by vico93** [comment]
This rep and (of course) Cauldron (official) developement is dead since wolvereness's bukkit DCMA.

BUT, we have a lifeboat: KCauldron: https://gitlab.prok.pw/Prototik/KCauldron
Download the KCauldron build in Yive Mirror (http://tcpr.ca/cauldron). If the issue persists, login and repost the issue in that rep!
